// import axios from 'axios';
let suratList = require('./quran/list.json');

let surahCollection = {
  1: require('./quran/surat/1.json'),
  2: require('./quran/surat/2.json'),
  3: require('./quran/surat/3.json'),
  4: require('./quran/surat/4.json'),
  5: require('./quran/surat/5.json'),
  6: require('./quran/surat/6.json'),
  7: require('./quran/surat/7.json'),
  8: require('./quran/surat/8.json'),
  9: require('./quran/surat/9.json'),
  10: require('./quran/surat/10.json'),
  11: require('./quran/surat/11.json'),
  12: require('./quran/surat/12.json'),
  13: require('./quran/surat/13.json'),
  14: require('./quran/surat/14.json'),
  15: require('./quran/surat/15.json'),
  16: require('./quran/surat/16.json'),
  17: require('./quran/surat/17.json'),
  18: require('./quran/surat/18.json'),
  19: require('./quran/surat/19.json'),
  20: require('./quran/surat/20.json'),
  21: require('./quran/surat/21.json'),
  22: require('./quran/surat/22.json'),
  23: require('./quran/surat/23.json'),
  24: require('./quran/surat/24.json'),
  25: require('./quran/surat/25.json'),
  26: require('./quran/surat/26.json'),
  27: require('./quran/surat/27.json'),
  28: require('./quran/surat/28.json'),
  29: require('./quran/surat/29.json'),
  30: require('./quran/surat/30.json'),
  31: require('./quran/surat/31.json'),
  32: require('./quran/surat/32.json'),
  33: require('./quran/surat/33.json'),
  34: require('./quran/surat/34.json'),
  35: require('./quran/surat/35.json'),
  36: require('./quran/surat/36.json'),
  37: require('./quran/surat/37.json'),
  38: require('./quran/surat/38.json'),
  39: require('./quran/surat/39.json'),
  40: require('./quran/surat/40.json'),
  41: require('./quran/surat/41.json'),
  42: require('./quran/surat/42.json'),
  43: require('./quran/surat/43.json'),
  44: require('./quran/surat/44.json'),
  45: require('./quran/surat/45.json'),
  46: require('./quran/surat/46.json'),
  47: require('./quran/surat/47.json'),
  48: require('./quran/surat/48.json'),
  49: require('./quran/surat/49.json'),
  50: require('./quran/surat/50.json'),
  51: require('./quran/surat/51.json'),
  52: require('./quran/surat/52.json'),
  53: require('./quran/surat/53.json'),
  54: require('./quran/surat/54.json'),
  55: require('./quran/surat/55.json'),
  56: require('./quran/surat/56.json'),
  57: require('./quran/surat/57.json'),
  58: require('./quran/surat/58.json'),
  59: require('./quran/surat/59.json'),
  60: require('./quran/surat/60.json'),
  61: require('./quran/surat/61.json'),
  62: require('./quran/surat/62.json'),
  63: require('./quran/surat/63.json'),
  64: require('./quran/surat/64.json'),
  65: require('./quran/surat/65.json'),
  66: require('./quran/surat/66.json'),
  67: require('./quran/surat/67.json'),
  68: require('./quran/surat/68.json'),
  69: require('./quran/surat/69.json'),
  70: require('./quran/surat/70.json'),
  71: require('./quran/surat/71.json'),
  72: require('./quran/surat/72.json'),
  73: require('./quran/surat/73.json'),
  74: require('./quran/surat/74.json'),
  75: require('./quran/surat/75.json'),
  76: require('./quran/surat/76.json'),
  77: require('./quran/surat/77.json'),
  78: require('./quran/surat/78.json'),
  79: require('./quran/surat/79.json'),
  80: require('./quran/surat/80.json'),
  81: require('./quran/surat/81.json'),
  82: require('./quran/surat/82.json'),
  83: require('./quran/surat/83.json'),
  84: require('./quran/surat/84.json'),
  85: require('./quran/surat/85.json'),
  86: require('./quran/surat/86.json'),
  87: require('./quran/surat/87.json'),
  88: require('./quran/surat/88.json'),
  89: require('./quran/surat/89.json'),
  90: require('./quran/surat/90.json'),
  91: require('./quran/surat/91.json'),
  92: require('./quran/surat/92.json'),
  93: require('./quran/surat/93.json'),
  94: require('./quran/surat/94.json'),
  95: require('./quran/surat/95.json'),
  96: require('./quran/surat/96.json'),
  97: require('./quran/surat/97.json'),
  98: require('./quran/surat/98.json'),
  99: require('./quran/surat/99.json'),
  100: require('./quran/surat/100.json'),
  101: require('./quran/surat/101.json'),
  102: require('./quran/surat/102.json'),
  103: require('./quran/surat/103.json'),
  104: require('./quran/surat/104.json'),
  105: require('./quran/surat/105.json'),
  106: require('./quran/surat/106.json'),
  107: require('./quran/surat/107.json'),
  108: require('./quran/surat/108.json'),
  109: require('./quran/surat/109.json'),
  110: require('./quran/surat/110.json'),
  111: require('./quran/surat/111.json'),
  112: require('./quran/surat/112.json'),
  113: require('./quran/surat/113.json'),
  114: require('./quran/surat/114.json'),
};

const API = {
  getSurah: async function () {
    return suratList;
  },
  getDetail: async function (params) {
    if (params) {
      let surat = surahCollection[params.suratId];
      return surat.data.filter(item => item.aya_number === params.ayat);
    }
    return null;
  },
};
export default API;
